language: python
python:
  - "2.7"
  - "3.5"

# env:
#   - VAR=var

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

# command to run tests
# script:
#   - python src/server.py test
#   - coverage run src/server.py test

after_success: coveralls
